---
title: "Stéphane Gonzalez"
---

## Biography
I am a Full Professor at the [Groupe d'analyse et de théorie économique (GATE Lyon Saint-Etienne)](https://www.gate.cnrs.fr/), UMR 5824, [University of Saint-Etienne](https://www.univ-st-etienne.fr/), and the [Saint-Etienne School of Economics (SE2)](https://se2.univ-st-etienne.fr/). Since January 2025, I have served as the **Deputy Director of GATE**, in charge of the Saint-Étienne site. I am also a **Coordinating Editor** at [*Theory and Decision*](https://www.springer.com/journal/11238).
I founded the [Master's program in Political Engineering](https://www.univ-st-etienne.fr/fr/formation/d-u-1/d-u-1/du-introduction-to-political-engineering-KVQTJNB1.html), which later evolved into the [Master's program in Economics and Data for Decision Science (EDDS)](https://se2.univ-st-etienne.fr/fr/etudier-a-se2/les-masters/economics-data-and-decision-science/master-economics-data-and-decision-science.html). I also lead and founded the [Microcertification Artificial Intelligence: Challenges, Opportunities & Practical Cases](https://se2.univ-st-etienne.fr/fr/etudier-a-se2/formation-continue/formation-certifiante-intelligence-artificielle.html).
My academic background spans both mathematics and economics, with a Master's in **Pure Mathematics** from [Université Paris-Saclay](https://www.universite-paris-saclay.fr/) and another in **Theoretical Economics** from [Université Paris 1 Panthéon-Sorbonne](https://www.pantheonsorbonne.fr/). I earned my PhD from Université Paris 1, affiliated with the [Centre d'Economie de la Sorbonne (CES)](https://ces.pantheonsorbonne.fr/) and the [Paris School of Economics (PSE)](https://www.parisschoolofeconomics.eu/), under the supervision of [Michel Grabisch](https://sites.google.com/site/michelgrabisch/).
My research and teaching center on **theoretical economics**, especially **game theory** and **social choice theory**, with a strong emphasis on the **axiomatic method**.
---

## Professional roles and supervision
* **Deputy Director of GATE Lyon Saint-Etienne** (since January 2025), in charge of the Saint-Étienne site.
* **Coordinating Editor**: [*Theory and Decision*](https://www.springer.com/journal/11238).
* **PhD supervision**: I have supervised two PhD students: [Kevin Techer](https://sites.google.com/view/kevintecher/home) and [David Lowing](https://sites.google.com/view/davidlowing/home).

## Research topics
- Economic Theory
- Game Theory
- Social Choice
- Coalition Formation

## Publications

1. **[An axiomatic characterization of the proportional threshold methods: A geometric approach](https://doi.org/10.1007/s00355-025-01618-6)**, Susumu Cato, Stéphane Gonzalez, Eric Rémila, Philippe Solal, *Social Choice and Welfare*, May 2026, Volume 66, 619–645.

1. **[Axiomatization and Implementation via objections structure](https://doi.org/10.1007/s11238-025-10051-1)**, Aymeric Lardon, Stéphane Gonzalez, *Theory and Decision*, September 2025, Volume 99, 393–405.

1. **[A Story of Consistency: Bridging the gap between Bentham and Rawls foundations](https://doi.org/10.1007/s11229-024-04612-0)**, Stéphane Gonzalez, Nikolaos Pnevmatikos, *Synthese*, June 2024, Volume 203, article number 208.

1. **[Axiomatic characterizations of the core without consistency](https://doi.org/10.1007/s00182-022-00835-y)**, Sylvain Béal, Stéphane Gonzalez, Philippe Solal, Peter Sudhölter, *International Journal of Game Theory*, September 2023, Volume 53(3), 687–701.

1. **[Sharing the Global Outcomes of Finite Natural Resource Exploitation: A Dynamic Coalitional Stability Perspective](https://doi.org/10.1016/j.mathsocsci.2022.05.003)**, Stéphane Gonzalez, Fatma Zahra Rostom, *Mathematical Social Sciences*, September 2022, Volume 119, 1–10.

1. **[Axiomatic foundations of the core for games in effectiveness form](https://doi.org/10.1016/j.mathsocsci.2021.09.001)**, Stéphane Gonzalez, Aymeric Lardon, *Mathematical Social Sciences*, November 2021, Volume 114, 28–38.

1. **[Approval voting without ballot restrictions](https://doi.org/10.3982/TE4087)**, Federica Ceron, Stéphane Gonzalez, *Theoretical Economics*, July 2021, Volume 16, Issue 3, 759–775.

1. **[INFLUENCE: A partizan scoring game on graphs](https://doi.org/10.1016/j.tcs.2021.05.028)**, Eric Duchêne, Stéphane Gonzalez, Aline Parreau, Eric Rémila, Philippe Solal, *Theoretical Computer Science*, July 2021, Volumes 878–879, 26–46.

1. **[Dilemma with approval and disapproval votes](https://doi.org/10.1007/s00355-019-01194-6)**, Stéphane Gonzalez, Annick Laruelle, Philippe Solal, *Social Choice and Welfare*, August 2019, Volume 53, Issue 3, 497–517.

1. **[The social cost problem, rights and the (non)empty core](https://doi.org/10.1111/jpet.12334)**, Stéphane Gonzalez, Alain Marciano, Philippe Solal, *Journal of Public Economic Theory*, April 2019, Volume 21, Issue 2, 347–365.

1. **[Optimal deterrence of cooperation](https://doi.org/10.1007/s00182-017-0584-8)**, Stéphane Gonzalez, Aymeric Lardon, *International Journal of Game Theory*, March 2018, Volume 47, Issue 1, 207–227.

1. **[De nouveaux éclairages sur le théorème de Coase et la vacuité du cœur à trois joueurs](https://www.cairn.info/revue-d-economie-politique-2017-4-page-579.htm)**, Stéphane Gonzalez, Alain Marciano, *Revue d'économie politique*, September 2017, Volume 127, Issue 4, 579–600.

1. **[Multicoalitional solutions](https://doi.org/10.1016/j.jmateco.2016.02.006)**, Stéphane Gonzalez, Michel Grabisch, *Journal of Mathematical Economics*, May 2016, Volume 64, 1–10.

1. **[Autonomous coalitions](https://doi.org/10.1007/s10479-015-1951-0)**, Stéphane Gonzalez, Michel Grabisch, *Annals of Operations Research*, December 2015, Volume 235, Issue 1, 301–317.

1. **[Preserving coalitional rationality for non-balanced games](https://doi.org/10.1007/s00182-014-0451-9)**, Stéphane Gonzalez, Michel Grabisch, *International Journal of Game Theory*, August 2015, Volume 44, Issue 3, 733–760.

## Working papers

1. **[Consistency in collective decision-making under uncertainty: an axiomatic approach](https://www.gate.cnrs.fr/RePEc/2026/2604.pdf)**, Stéphane Gonzalez, Le-Nhat-Linh Huynh.
1. **[An Axiomatic Characterization of the Knapsack Budget Allocation Rule](https://drive.google.com/file/d/1ohZOChhUraWmsfbry4vOygneIh3gKfo3/view)**, Federica Ceron, Stéphane Gonzalez, Adriana Navarro Ramos.
1. **[Approval voting versus proportional threshold methods: so far and yet so near](https://shs.hal.science/halshs-03858356)**, Susumu Cato, Stéphane Gonzalez, Eric Rémila, Philippe Solal.
1. **Filters in abstract aggregation with infinite sequences of signals**, Susumu Cato, Stéphane Gonzalez, Eric Rémila, Philippe Solal.

## List of peer-reviewed international conference presentations

1. ASSET (Rabat, Morocco, 2025)
1. SAET 24 (Ischia, Italy, 2025)
1. SING 20 (Maastricht, Netherlands, 2025)
1. SING 19 (Besançon, France, 2024)
1. SSCW 17 (Paris, France, 2024)
1. PET 2024 (Lyon, France, 2024)
1. SAET 23 (Santiago, Chile, 2024)
1. SAET 22 (Paris, France, 2023)
1. SING 18 (Messina, Italy, 2023)
1. EURO OR 2022 (Espoo, Finland, 2022)
1. EURO OR 2021 (Athens, virtual, Greece, 2021)
1. PET (Strasbourg, France, 2019)
1. SAET 19 (Ischia, Italy, 2019)
1. CESC 2 (Barcelona, Spain, 2019)
1. SING 14 (Bayreuth, Germany, 2018)
1. EURO 2018 – ECOR 29 (Valencia, Spain, 2018)
1. Paris Symposium on Games 2018 (Paris, France, 2018)
1. PET (Paris, France, 2017)
1. SAET 17 (Faro, Portugal, 2017)
1. Journées LAGV (Aix-en-Provence, France, 2017)
1. CESC (Barcelona, Spain, 2017)
1. SING 12 (Odense, Denmark, 2016)
1. EURO 2016 – ECOR 28 (Poznan, Poland, 2016)
1. SSCW 13 (Lund, Sweden, 2016)
1. SING 11 (St-Petersburg, Russia, 2015)
1. SING 10 (Krakow, Poland, 2014)
1. SAET 13 (Paris, France, 2013)
1. SING 9 (Vigo, Spain, 2013)
1. SING 8 (Budapest, Hungary, 2012)
1. SING 7 (Paris, France, 2011)

## Invitations to participate in workshops, seminars, and conferences

1. AGATE Seminar, Charles University (Prague, Czech Republic, 2026)
1. OSGAD 18, in honor of Michel Grabisch (Paris, France, 2025)
1. Game Theory Workshop in Honour of Peter Sudhölter (Universitat Roviri i Virgili, Spain, 2025)
1. Economics Seminar of Bielefeld University (Bielefeld, Germany, 2025)
1. OSGAD 17 (Paris, France, 2024)
1. GT Économie Comportementale (Université Paris Nanterre, France, 2024)
1. Participatory Budgeting Workshop (Paris School of Economics, France, 2024)
1. Amsterdam/Saint-Etienne Workshop on Social Choice (Saint-Etienne, France, 2024)
1. Séminaire du CREM (Caen, France, 2024)
1. 2nd UB Workshop on Game Theory (Barcelona, Spain, 2023)
1. Online Social Choice and Welfare Seminar (Online, 2023)
1. XXXI European Workshop on Economic Theory – EWET (Naples, Italy, 2023)
1. CO2ERASE (University Paris Dauphine, France, 2023)
1. Workshop on Collective Decisions: Current Trends (Granada, Spain, 2023)
1. Seminar of Economics and Management (University of Paderborn, Germany, 2023)
1. Economic theory seminar (CES, Paris, France, 2023)
1. Interaction seminar (AMSE, Marseille, France, 2022)
1. Workshop GDR-Jeux cooperative models in games and social choice (CRESE, Besançon, France, 2022)
1. Game theory seminar (University of Barcelona, Spain, 2022)
1. MDOD Seminar (Paris 1, France, 2021)
1. Séminaire du CRESE (Besançon, France, 2020)
1. LEM Seminar (Lille, France, 2020)
1. LED Seminar (Paris 8, France, 2019)
1. MRE Seminar (Montpellier, France, 2019)
1. Paris Symposium on Games 2018 (Paris, France, 2018)
1. Symposium "Mathematics and Politics: Democratic Decision Making" (Hannover, Germany, 2018)
1. The Game Theory seminars of the University of the Basque Country (Bilbao, Spain, 2018)
1. CES Economic Theory Seminar of Paris 1 (Paris, France, 2018)
1. Séminaire du BETA (Nancy, France, 2018)
1. OSGAD 11 (Paris, France, 2017)
1. Axiomatizations in Game Theory (Pécs, Hungary, 2017)
1. Workshop MARS (Saint-Etienne, France, 2017)
1. Workshop Causation and Responsibility: Law, Economics, Philosophy (Nancy, France, 2016)
1. Séminaire du GATE-LSE (Lyon, France, 2016)
1. ADRES (Paris, France, 2015)
1. CEREC Workshop in Economics (Brussels, Belgium, 2014)
1. QED (Vienna, Austria, 2013)
1. MINT 4 (Amsterdam, Netherlands, 2013)
1. Séminaire du laboratoire EQUIPPE (Lille, France, 2013)
1. Parisian Game Theory PhD Seminar IHP (Paris, France, 2013)
1. PSE Seminar in Economic Theory (Paris, France, 2013)
1. OWL Workshop “Markets, Games, and Design” MGD12 (Paderborn, Germany, 2012)
1. EBIM Networks Workshop (Bielefeld, Germany, 2012)
1. OSGAD 5 (Paris, France, 2011)
