---
title: "Research"
description-meta: "Research, publications, working papers, conference presentations and invited seminars of Stéphane Gonzalez, Professor of Economics at Université Jean Monnet and GATE Lyon Saint-Étienne."
---

## Research topics
- Economic Theory
- Game Theory
- Social Choice
- Coalition Formation

## Publications
1. **[Filters in abstract aggregation with infinite sequences of signals](https://doi.org/10.1016/j.mathsocsci.2026.102551)**, Susumu Cato, Stéphane Gonzalez, Eric Rémila, Philippe Solal, *Mathematical Social Sciences*, July 2026.

1. **[An axiomatic characterization of the proportional threshold methods: A geometric approach](https://doi.org/10.1007/s00355-025-01618-6)**, Susumu Cato, Stéphane Gonzalez, Eric Rémila, Philippe Solal, *Social Choice and Welfare*, May 2026, Volume 66, 619–645.

1. **[Axiomatization and Implementation via objections structure](https://doi.org/10.1007/s11238-025-10051-1)**, Aymeric Lardon, Stéphane Gonzalez, *Theory and Decision*, September 2025, Volume 99, 393–405.

1. **[A Story of Consistency: Bridging the gap between Bentham and Rawls foundations](https://doi.org/10.1007/s11229-024-04612-0)**, Stéphane Gonzalez, Nikolaos Pnevmatikos, *Synthese*, June 2024, Volume 203, article number 208.

1. **[Axiomatic characterizations of the core without consistency](https://doi.org/10.1007/s00182-022-00835-y)**, Sylvain Béal, Stéphane Gonzalez, Philippe Solal, Peter Sudhölter, *International Journal of Game Theory*, September 2023, Volume 53(3), 687–701.

1. **[Sharing the Global Outcomes of Finite Natural Resource Exploitation: A Dynamic Coalitional Stability Perspective](https://doi.org/10.1016/j.mathsocsci.2022.05.003)**, Stéphane Gonzalez, Fatma Zahra Rostom, *Mathematical Social Sciences*, September 2022, Volume 119, 1–10.

1. **[Axiomatic foundations of the core for games in effectiveness form](https://doi.org/10.1016/j.mathsocsci.2021.09.001)**, Stéphane Gonzalez, Aymeric Lardon, *Mathematical Social Sciences*, November 2021, Volume 114, 28–38.

1. **[Approval voting without ballot restrictions](https://doi.org/10.3982/TE4087)**, Federica Ceron, Stéphane Gonzalez, *Theoretical Economics*, July 2021, Volume 16, Issue 3, 759–775.

1. **[INFLUENCE: A partizan scoring game on graphs](https://doi.org/10.1016/j.tcs.2021.05.028)**, Eric Duchêne, Stéphane Gonzalez, Aline Parreau, Eric Rémila, Philippe Solal, *Theoretical Computer Science*, July 2021, Volumes 878–879, 26–46.

1. **[Dilemma with approval and disapproval votes](https://doi.org/10.1007/s00355-019-01194-6)**, Stéphane Gonzalez, Annick Laruelle, Philippe Solal, *Social Choice and Welfare*, August 2019, Volume 53, Issue 3, 497–517.

1. **[The social cost problem, rights and the (non)empty core](https://doi.org/10.1111/jpet.12334)**, Stéphane Gonzalez, Alain Marciano, Philippe Solal, *Journal of Public Economic Theory*, April 2019, Volume 21, Issue 2, 347–365.

1. **[Optimal deterrence of cooperation](https://doi.org/10.1007/s00182-017-0584-8)**, Stéphane Gonzalez, Aymeric Lardon, *International Journal of Game Theory*, March 2018, Volume 47, Issue 1, 207–227.

1. **[De nouveaux éclairages sur le théorème de Coase et la vacuité du cœur à trois joueurs](https://www.cairn.info/revue-d-economie-politique-2017-4-page-579.htm)**, Stéphane Gonzalez, Alain Marciano, *Revue d'économie politique*, September 2017, Volume 127, Issue 4, 579–600.

1. **[Multicoalitional solutions](https://doi.org/10.1016/j.jmateco.2016.02.006)**, Stéphane Gonzalez, Michel Grabisch, *Journal of Mathematical Economics*, May 2016, Volume 64, 1–10.

1. **[Autonomous coalitions](https://doi.org/10.1007/s10479-015-1951-0)**, Stéphane Gonzalez, Michel Grabisch, *Annals of Operations Research*, December 2015, Volume 235, Issue 1, 301–317.

1. **[Preserving coalitional rationality for non-balanced games](https://doi.org/10.1007/s00182-014-0451-9)**, Stéphane Gonzalez, Michel Grabisch, *International Journal of Game Theory*, August 2015, Volume 44, Issue 3, 733–760.

## Working papers

1. **[Approval Voting with Fixed Electorates, Fixed Agendas and No Ballot Assumptions](https://hal.science/hal-05717382)**, Raffaele Berzi, Stéphane Gonzalez.
1. **[Consistency in collective decision-making under uncertainty: an axiomatic approach](https://www.gate.cnrs.fr/RePEc/2026/2604.pdf)**, Stéphane Gonzalez, Le-Nhat-Linh Huynh.
1. **[An Axiomatic Characterization of the Knapsack Budget Allocation Rule](https://drive.google.com/file/d/1ohZOChhUraWmsfbry4vOygneIh3gKfo3/view)**, Federica Ceron, Stéphane Gonzalez, Adriana Navarro Ramos.
1. **[Approval voting versus proportional threshold methods: so far and yet so near](https://shs.hal.science/halshs-03858356)**, Susumu Cato, Stéphane Gonzalez, Eric Rémila, Philippe Solal.

## List of peer-reviewed international conference presentations

1. [SING 21](https://sites.google.com/view/sing-21/) (Naples, Italy, 2026)
1. [SSCW 18](https://sites.google.com/view/sscw2026) (Tokyo, Japan, 2026)
1. [ASSET](https://airess.fgses-um6p.ma/asset2025) (Rabat, Morocco, 2025)
1. [SAET 24](https://saet.uiowa.edu/2025-conference/) (Ischia, Italy, 2025)
1. [SING 20](https://sites.google.com/view/sing20) (Maastricht, Netherlands, 2025)
1. [SING 19](https://univfcomte.wixsite.com/sing19) (Besançon, France, 2024)
1. [SSCW 17](https://scwsociety.org/2024-Meeting.html) (Paris, France, 2024)
1. [PET 2024](https://pet2024.sciencesconf.org/) (Lyon, France, 2024)
1. [SAET 23](https://saet.uiowa.edu/saet-conference-january-8-11-2024-santiago-chile-2/) (Santiago, Chile, 2024)
1. [SAET 22](https://sites.google.com/view/saet2023/home) (Paris, France, 2023)
1. [SING 18](https://epoc-itn.eu/en/events/epoc-international-conference/18th-european-meeting-on-game-theory/2023-06-26/55/) (Messina, Italy, 2023)
1. [EURO OR 2022](https://euro2022.euro-online.org/index.html) (Espoo, Finland, 2022)
1. [EURO OR 2021](https://www.euro-online.org/websites/or-in-practice/event/euro-2021/) (Athens, virtual, Greece, 2021)
1. [PET](https://www.afse.fr/fr/news/international-conference-on-public-economic-theory-8-11th-july-2019-1848) (Strasbourg, France, 2019)
1. [SAET 19](https://saet.uiowa.edu/2019-conference-page/) (Ischia, Italy, 2019)
1. [CESC 2](https://cesc.iec.cat/en/index.html) (Barcelona, Spain, 2019)
1. [SING 14](https://sing14.org/) (Bayreuth, Germany, 2018)
1. [EURO 2018 – ECOR 29](https://euro2018.euro-online.org/index.html) (Valencia, Spain, 2018)
1. [Paris Symposium on Games 2018](https://gametheorysociety.org/paris-symposium-on-game-theory-2018/) (Paris, France, 2018)
1. [PET](https://pet2017paris2.sciencesconf.org/) (Paris, France, 2017)
1. [SAET 17](https://saet.uiowa.edu/past-events/saet2017/) (Faro, Portugal, 2017)
1. [Journées LAGV](https://lagv2021.sciencesconf.org/) (Aix-en-Provence, France, 2017)
1. [CESC](https://editorialexpress.com/conference/CESC2017/) (Barcelona, Spain, 2017)
1. [SING 12](https://sites.google.com/unisa.it/sing/history) (Odense, Denmark, 2016)
1. [EURO 2016 – ECOR 28](https://euro2016.euro-online.org/) (Poznan, Poland, 2016)
1. [SSCW 13](https://editorialexpress.com/conference/SCW2016/program/SCW2016.html) (Lund, Sweden, 2016)
1. [SING 11](https://sites.google.com/unisa.it/sing/history) (St-Petersburg, Russia, 2015)
1. [SING 10](https://www.sing10.zarz.agh.edu.pl/) (Krakow, Poland, 2014)
1. [SAET 13](https://saet.uiowa.edu/past-events/saet2013/) (Paris, France, 2013)
1. [SING 9](https://gametheorysociety.org/9th-spain-italy-netherlands-meeting-on-game-theory-sing9/) (Vigo, Spain, 2013)
1. [SING 8](https://gametheorysociety.org/sing8-the-8th-spain-italy-netherlands-meeting-on-game-theory/) (Budapest, Hungary, 2012)
1. [SING 7](https://gametheorysociety.org/sing7-spain-italy-and-netherlands-meeting-on-game-theory/) (Paris, France, 2011)

## Invitations to participate in workshops, seminars, and conferences

1. [GRC Game Theory Workshop](https://funaki.w.waseda.jp/kenkyu2024.html), Waseda University, (Tokyo, Japan, 2026)
1. [Economics and Game Theory Seminar (経済学・ゲーム理論セミナー)](https://sites.google.com/view/tus-gametheory/), Tokyo University of Science, (Tokyo, Japan, 2026)
1. [Game Theory, Social Choice, and Mechanism Design](https://www.linkedin.com/posts/forum-geni-insea_forumgeniinsea-workshop-insea-activity-7450325066686484480-QvBS), INSEA (Rabat, Morocco, 2026)
1. [AGATE Seminar](https://centre.agate.cuni.cz/), Charles University (Prague, Czech Republic, 2026)
1. [OSGAD 18, in honor of Michel Grabisch](https://ces.pantheonsorbonne.fr/en/news/workshop-osgad-honor-michel-grabisch) (Paris, France, 2025)
1. [Game Theory Workshop in Honour of Peter Sudhölter](https://www.eco-sos.urv.cat/es/agenda/5696/workshop-de-teoria-de-juegos-en-honor-a-peter-sudhoelter) (Universitat Roviri i Virgili, Spain, 2025)
1. [Economics Seminar of Bielefeld University](https://www.uni-bielefeld.de/fakultaeten/wirtschaftswissenschaften/einrichtungen/bigsem/profiles/economics/economics-seminar/) (Bielefeld, Germany, 2025)
1. [OSGAD 17](https://ces.pantheonsorbonne.fr/evenements/17e-seminaire-osgad-structures-ordonnees-dans-jeux-et-decision) (Paris, France, 2024)
1. [GT Économie Comportementale](https://economix.fr/fr/economie-comportementale) (Université Paris Nanterre, France, 2024)
1. [Participatory Budgeting Workshop](https://sites.google.com/site/cesworkinggroupnetworks/workshops-conferences) (Paris School of Economics, France, 2024)
1. [Amsterdam/Saint-Etienne Workshop on Social Choice](https://www.gate.cnrs.fr/en/news/2nd-amsterdam-saint-etienne-workshop-on-social-choice/) (Saint-Etienne, France, 2024)
1. [Séminaire du CREM](https://crem.unicaen.fr/) (Caen, France, 2024)
1. [2nd UB Workshop on Game Theory](https://www.ub.edu/gametheory/events/annual-workshop/) (Barcelona, Spain, 2023)
1. [Online Social Choice and Welfare Seminar](https://groups.google.com/g/social-choice-and-welfare-forum/c/BR836OIRzVo) (Online, 2023)
1. [XXXI European Workshop on Economic Theory – EWET](https://csef.it/Event/xxxi-european-workshop-on-economic-theory-ewet-2023/) (Naples, Italy, 2023)
1. [CO2ERASE](https://hal.inrae.fr/hal-04177039) (University Paris Dauphine, France, 2023)
1. [Workshop on Collective Decisions: Current Trends](https://secretariageneral.ugr.es/sites/webugr/secretariageneral/public/inline-files/MA_2022-2023/174%20OFICINA%20WEB.pdf) (Granada, Spain, 2023)
1. [Seminar of Economics and Management](https://wiwi.uni-paderborn.de/en/forschen/seminare-workshops-und-qualifizierungsangebote/seam/archive) (University of Paderborn, Germany, 2023)
1. [Economic theory seminar](https://ces.pantheonsorbonne.fr/en/economic-theory-2) (CES, Paris, France, 2023)
1. [Interaction seminar](https://www.amse-aixmarseille.fr/fr/evenements/st%C3%A9phane-gonzalez) (AMSE, Marseille, France, 2022)
1. [Workshop GDR-Jeux cooperative models in games and social choice](https://sites.google.com/view/gdr-jeux-crese/home) (CRESE, Besançon, France, 2022)
1. [Game theory seminar](https://www.ub.edu/gametheory/events/seminars/past-seminars-archive/) (University of Barcelona, Spain, 2022)
1. [MDOD Seminar](https://ces.pantheonsorbonne.fr/en/research/seminars) (Paris 1, France, 2021)
1. [Séminaire du CRESE](https://crese.univ-fcomte.fr/) (Besançon, France, 2020)
1. [LEM Seminar](https://lem.univ-lille.fr/detail-event/seminaire-mof-/-adp-58) (Lille, France, 2020)
1. [LED Seminar](https://sciences-sociales.univ-paris8.fr/IMG/pdf/seminaires_et_colloques_ed_et_labo_2018-2019_travail_maj_19_04_2019.pdf) (Paris 8, France, 2019)
1. [MRE Seminar](https://mre.edu.umontpellier.fr/en/le-seminaire-de-mre/) (Montpellier, France, 2019)
1. [Paris Symposium on Games 2018](https://gametheorysociety.org/paris-symposium-on-game-theory-2018/) (Paris, France, 2018)
1. [Symposium "Mathematics and Politics: Democratic Decision Making"](https://findresearcher.sdu.dk/ws/portalfiles/portal/cv/7077ff8b-a9a7-45ec-a32d-4479b748229b?locale=en_GB) (Hannover, Germany, 2018)
1. [The Game Theory seminars of the University of the Basque Country](https://www.ehu.eus/en/web/analisi-ekonomikoa-saila/seminars) (Bilbao, Spain, 2018)
1. [CES Economic Theory Seminar of Paris 1](https://ces.pantheonsorbonne.fr/en/economic-theory-2) (Paris, France, 2018)
1. [Séminaire du BETA](https://www.beta-economics.fr/seminaires/) (Nancy, France, 2018)
1. [OSGAD 11](https://orbilu.uni.lu/bitstream/10993/32981/4/Programme.pdf) (Paris, France, 2017)
1. [Axiomatizations in Game Theory](https://gametheorysociety.org/axiomatizations-in-game-theory/) (Pécs, Hungary, 2017)
1. [Workshop MARS](https://sites.google.com/site/coalitionsnetworks/) (Saint-Etienne, France, 2017)
1. [Workshop Causation and Responsibility: Law, Economics, Philosophy](https://www.univ-lorraine.fr/) (Nancy, France, 2016)
1. [Séminaire du GATE-LSE](https://www.gate.cnrs.fr/) (Lyon, France, 2016)
1. [ADRES](https://www.association-adres.fr/) (Paris, France, 2015)
1. [CEREC Workshop in Economics](https://cerec.be/) (Brussels, Belgium, 2014)
1. [QED](https://economics.univie.ac.at/) (Vienna, Austria, 2013)
1. [MINT 4](https://www.tinbergen.nl/) (Amsterdam, Netherlands, 2013)
1. [Séminaire du laboratoire EQUIPPE](https://lem.univ-lille.fr/) (Lille, France, 2013)
1. [Parisian Game Theory PhD Seminar IHP](https://sites.google.com/site/oliubarton/game-theory-phd-seminar-1) (Paris, France, 2013)
1. [PSE Seminar in Economic Theory](https://www.parisschoolofeconomics.eu/en/news/seminars/) (Paris, France, 2013)
1. [OWL Workshop “Markets, Games, and Design” MGD12](https://wiwi.uni-paderborn.de/fileadmin-wiwi/fakultaet/Fakultaet/ueber_die_Fakultaet/Jahresberichte/2011-2013_UPB_WIWI_FACULTY_in_FOCUS.pdf) (Paderborn, Germany, 2012)
1. [EBIM Networks Workshop](https://www.uni-bielefeld.de/fakultaeten/wirtschaftswissenschaften/) (Bielefeld, Germany, 2012)
1. [OSGAD 5](https://sites.google.com/view/osgad/accueil) (Paris, France, 2011)

## Workshop organization

1. **[19th Meeting of the Society for Social Choice and Welfare (SSCW 2028)](https://www.gate.cnrs.fr/condorcet/)** — Co-organizer. Lyon, France, 2028.
1. **[France–Spain Meeting on Microeconomic Theory](https://sites.google.com/go.ugr.es/france-spain-mit)** — Member of the Scientific Committee.
1. **[Workshop in Economic Theory](https://economic-theory-stetienne.github.io/)** — Co-organizer. Saint-Étienne, France, September 8, 2026.
1. **[SAET 2025](https://saet.uiowa.edu/2025-conference/)** — Co-organizer with Federica Ceron of the session *Axiomatization in Economic Theory*. Ischia, Italy, 2025.
1. **[SAET 2024](https://saet.uiowa.edu/saet-conference-january-8-11-2024-santiago-chile-2/)** — Co-organizer with Federica Ceron of two sessions on *Axiomatization in Economic Theory*. Santiago, Chile, 2024.
1. **[SAET 2023](https://sites.google.com/view/saet2023/home)** — Organizer of a session on *Axiomatization in Economic Theory*. Paris, France, 2023.
1. **[Games and Optimization 2022 (GO22)](https://go22.sciencesconf.org/?lang=en)** — Co-organizer with Eric Rémila. Saint-Étienne, France, April 14–15, 2022.
1. **INDEPTH #1 — Institutional Design and Economic Preferences: Theory and Experiments** — Co-organizer. Saint-Étienne, France, March 28–29, 2019.
1. **Journées SDA2 2018 — Systèmes Dynamiques, Automates & Algorithmes** — Member of the organizing committee. Saint-Étienne, France, July 2018.
1. **[MARS — Measures, Axioms, Rights and Stability in Coalitions and Networks](https://sites.google.com/site/coalitionsnetworks/)** — Organizer. Saint-Étienne, France, March 22–23, 2017.
1. **Faire de la politique autrement? Théorie et pratique du choix social** — Co-organizer with Antoinette Baujard and Mostapha Diss. Saint-Étienne, France, April 27–28, 2017.
1. **Games and Optimization** — Co-organizer. Saint-Étienne, France, November 21–22, 2017.
1. **ADRES Doctoral Conference** — Member of the Scientific Committee, 2020–2023.
